source 'https://github.com/CocoaPods/Specs'
source 'https://git-externe.rennes.ariadnext.com/idcheckio/axt-podspecs.git'

platform :ios, '10.0'

# Uncomment this line if you use Swift
use_frameworks!

target 'IDCheckioSDK_Sample' do
  # Application Pods
  pod 'IDCheckIOSDK', '5.7.0'

end

abstract_target :unit_tests do
  target 'UnitTests'
  pod 'Specta'
  pod 'Expecta'
  pod 'OCMock'
  pod 'OHHTTPStubs'
end


# Copy acknowledgements to the Settings.bundle

post_install do | installer |
  require 'fileutils'

  pods_acknowledgements_path = 'Pods/Target Support Files/Pods/Pods-Acknowledgements.plist'
  settings_bundle_path = Dir.glob("**/*Settings.bundle*").first

  if File.file?(pods_acknowledgements_path)
    puts 'Copying acknowledgements to Settings.bundle'
    FileUtils.cp_r(pods_acknowledgements_path, "#{settings_bundle_path}/Acknowledgements.plist", :remove_destination => true)
  end
end
