# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://git-externe.rennes.ariadnext.com/idcheckio/axt-podspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'idcheckio-sdk-sample-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :ios, '12.0'
  # Pods for idcheckio-sdk-sample-ios
  pod 'IDCheckIOSDK', '6.1.0'

end
